apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-redmine-ish-app
  namespace: go-redmine-ish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-redmine-ish-app
  template:
    metadata:
      labels:
        app: vite-redmine-ish-app
    spec:
      containers:
        - name: vite-redmine-ish-app-nginx
          image: localhost:32000/vite-redmine-ish-app:latest
          ports:
            - name: http-port
              containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 5Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
