apiVersion: v1
kind: Service
metadata:
  name: vite-redmine-ish-app-service
  namespace: go-redmine-ish
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80 # Debe coincidir con el puerto expuesto por el contenedor
      protocol: TCP
  selector:
    app: vite-redmine-ish-app # Asegúrate de que coincida con las etiquetas del pod
